sonar.projectKey=UlyssouLV_ArgOS
sonar.organization=ulyssoulv
sonar.sources=api,web
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/uv.lock,media/**,**/node_modules/**,web/dist/**
sonar.coverage.exclusions=**/migrations/**,tests/**
