sonar.projectKey=UlyssouLV_ArgOS
sonar.organization=ulyssoulv
sonar.sources=api
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/uv.lock,media/**
sonar.coverage.exclusions=**/migrations/**,tests/**
